// Bay LMS Contract Addresses and ABIs
// 공통 패키지에서 import하여 중복 제거

import {
  CONTRACTS,
  EAS_ADDRESS,
  SCHEMA_REGISTRY,
  MOCK_TOKEN_ABI,
  DEPOSIT_ESCROW_ABI,
  ASSIGNMENT_REGISTRY_ABI,
  COHORT_MANAGER_ABI,
  BAY_CERTIFICATE_ABI,
  MOCK_TOKEN_CONTRACT,
  DEPOSIT_ESCROW_CONTRACT,
  BAY_CERTIFICATE_CONTRACT,
} from "@bay-lms/shared";

// 모든 exports
export {
  CONTRACTS,
  EAS_ADDRESS,
  SCHEMA_REGISTRY,
  MOCK_TOKEN_ABI,
  DEPOSIT_ESCROW_ABI,
  ASSIGNMENT_REGISTRY_ABI,
  COHORT_MANAGER_ABI,
  BAY_CERTIFICATE_ABI,
  MOCK_TOKEN_CONTRACT,
  DEPOSIT_ESCROW_CONTRACT,
  BAY_CERTIFICATE_CONTRACT,
};

// 레거시 호환성을 위한 re-export
export const MOCK_TOKEN = MOCK_TOKEN_CONTRACT;
export const DEPOSIT_ESCROW = DEPOSIT_ESCROW_CONTRACT;
